// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.1";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.1";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in CRM user's id and email.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = { user_id: ctx.getUserId(), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-workspaces.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.1";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  if (!url || !key) throw new Error("Supabase env not configured");
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data) }],
    structuredContent: data
  };
}

// src/lib/mcp/tools/list-workspaces.ts
var list_workspaces_default = defineTool2({
  name: "list_workspaces",
  title: "List my CRM workspaces",
  description: "List CRM workspaces the signed-in user is a member of.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("crm_workspace_members").select("workspace_id, role, crm_workspaces(id, name, slug)").eq("user_id", ctx.getUserId());
    if (error) return errorResult(error.message);
    return jsonResult({ workspaces: data ?? [] });
  }
});

// src/lib/mcp/tools/list-leads.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z } from "npm:zod@^3.25.76";
var list_leads_default = defineTool3({
  name: "list_leads",
  title: "List leads",
  description: "List CRM leads in a workspace. Results honor the signed-in user's access.",
  inputSchema: {
    workspace_id: z.string().uuid().describe("Workspace ID (from list_workspaces)."),
    limit: z.number().int().min(1).max(100).default(25).describe("Maximum number of leads to return."),
    status: z.string().optional().describe("Optional status filter (e.g. new, qualified).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ workspace_id, limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const sb = supabaseForUser(ctx);
    let q = sb.from("crm_leads").select("id, name, email, phone, status, source, created_at").eq("workspace_id", workspace_id).order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult({ leads: data ?? [] });
  }
});

// src/lib/mcp/tools/list-deals.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_deals_default = defineTool4({
  name: "list_deals",
  title: "List deals",
  description: "List CRM deals in a workspace, most recent first.",
  inputSchema: {
    workspace_id: z2.string().uuid(),
    limit: z2.number().int().min(1).max(100).default(25),
    stage: z2.string().optional().describe("Optional stage filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ workspace_id, limit, stage }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const sb = supabaseForUser(ctx);
    let q = sb.from("crm_deals").select("id, title, amount, currency, stage, probability, close_date, created_at").eq("workspace_id", workspace_id).order("created_at", { ascending: false }).limit(limit);
    if (stage) q = q.eq("stage", stage);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult({ deals: data ?? [] });
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_tasks_default = defineTool5({
  name: "list_tasks",
  title: "List tasks",
  description: "List CRM tasks in a workspace, most recent first.",
  inputSchema: {
    workspace_id: z3.string().uuid(),
    limit: z3.number().int().min(1).max(100).default(25),
    status: z3.string().optional().describe("Optional status filter (e.g. open, done).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ workspace_id, limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const sb = supabaseForUser(ctx);
    let q = sb.from("crm_tasks").select("id, title, status, priority, due_date, assignee_id, created_at").eq("workspace_id", workspace_id).order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult({ tasks: data ?? [] });
  }
});

// src/lib/mcp/tools/create-lead.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z as z4 } from "npm:zod@^3.25.76";
var create_lead_default = defineTool6({
  name: "create_lead",
  title: "Create lead",
  description: "Create a new lead in a CRM workspace for the signed-in user.",
  inputSchema: {
    workspace_id: z4.string().uuid(),
    name: z4.string().trim().min(1),
    email: z4.string().email().optional(),
    phone: z4.string().trim().max(30).optional(),
    source: z4.string().trim().max(60).optional(),
    notes: z4.string().max(4e3).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ workspace_id, name, email, phone, source, notes }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("crm_leads").insert({
      workspace_id,
      name,
      email: email ?? null,
      phone: phone ?? null,
      source: source ?? "mcp",
      notes: notes ?? null,
      created_by: ctx.getUserId()
    }).select("id, name, email, phone, status, source, created_at").single();
    if (error) return errorResult(error.message);
    return jsonResult({ lead: data });
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z as z5 } from "npm:zod@^3.25.76";
var create_task_default = defineTool7({
  name: "create_task",
  title: "Create task",
  description: "Create a new CRM task in a workspace for the signed-in user.",
  inputSchema: {
    workspace_id: z5.string().uuid(),
    title: z5.string().trim().min(1),
    description: z5.string().max(4e3).optional(),
    due_date: z5.string().datetime().optional().describe("ISO 8601 datetime for the due date."),
    priority: z5.enum(["low", "medium", "high"]).default("medium")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ workspace_id, title, description, due_date, priority }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("crm_tasks").insert({
      workspace_id,
      title,
      description: description ?? null,
      due_date: due_date ?? null,
      priority,
      status: "open",
      created_by: ctx.getUserId(),
      assignee_id: ctx.getUserId()
    }).select("id, title, status, priority, due_date, created_at").single();
    if (error) return errorResult(error.message);
    return jsonResult({ task: data });
  }
});

// src/lib/mcp/index.ts
var projectRef = "sfjxughxjvbuhocbmggp";
var mcp_default = defineMcp({
  name: "amruta-crm-mcp",
  title: "Amruta CRM",
  version: "0.1.0",
  instructions: "Tools to read and manage Amruta CRM data (workspaces, leads, deals, tasks) as the signed-in user. Call `list_workspaces` first to get a `workspace_id` for the other tools.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_workspaces_default, list_leads_default, list_deals_default, list_tasks_default, create_lead_default, create_task_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
